name: 📄 Documentation Issue
description: Report an issue with the documentation
title: "[Doc]: <Write a concise title here>"
body:
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see whether the issue you are encountering has already been reported.
      options:
        - label: I have searched the existing
            [issues](https://github.com/trvswgnr/sloth-pipe/issues)
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue with the documentation.
    validations:
      required: true
  - type: textarea
    id: page-section
    attributes:
      label: Page/Section
      description: Specify the page or section of the documentation where you encountered the problem.
    validations:
      required: false
  - type: textarea
    id: current-doc
    attributes:
      label: Current Documentation
      description: Provide the current content of the documentation related to the issue, if applicable.
    validations:
      required: false
  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: Suggest a clear and concise improvement to the documentation.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description:
        Add any additional context or information that might help in addressing the
        documentation issue.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our package are you running?
      placeholder: ex. 0.0.7
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: ex. Windows 10, Mac 14, Ubuntu 23 [...]
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: "What browsers are you seeing the problem on?"
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Brave
        - Opera
        - Other
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: willing-to-work
    attributes:
      label: "Are you willing to work on this issue?"
      options:
        - label: "Yes I am. (leave this unchecked for No)"
          required: false
